name: PHPUnit

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.0']
    name: Testing on PHP ${{ matrix.php-versions }}
    steps:
      - name: 'Checkout Project'
        uses: actions/checkout@v2

      - name: 'Setup Environment'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug

      - name: 'Setup Problem Matches'
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: 'Install Dependencies'
        run: composer install --ignore-platform-reqs

      - name: 'PHPUnit'
        uses: php-actions/phpunit@v3
        with:
          php_extensions: xdebug gd imagick
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
