name: PHPUnit

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1']
    name: Testing on PHP ${{ matrix.php-versions }}
    steps:
      - name: 'Checkout Project'
        uses: actions/checkout@v2

      - name: 'Setup Environment'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: imagick,gd,mbstring,bcmath
          tools: phpunit,composer

      - name: 'Install Dependencies'
        run: composer install --ignore-platform-reqs

      - name: PHP STatic ANalyser (phpstan)
        uses: chindit/actions-phpstan@1.0.1

      - name: PHPUnit
        uses: chindit/actions-phpunit@master
