name: PHPUnit

on: [workflow_dispatch]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.0']
    name: Testing on PHP ${{ matrix.php-versions }}
    steps:
      - name: 'Checkout Project'
        uses: actions/checkout@v2

      - name: 'Install PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, zip, gd, imagick, fileinfo
          tools: composer:v2

      - name: 'Update composer'
        run: composer self-update

      - name: 'Get composer cache directory'
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: 'Cache dependencies'
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: 'Install Dependencies'
        run: composer install --ignore-platform-reqs --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: 'PHPUnit'
        uses: php-actions/phpunit@v3
        with:
          php_extensions: gd imagick
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
          memory_limit: 128M
